### ISSUE TITLE
Create a endpoint to upload post and push the event data

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/off-chain-agent#34]
## Description
- add an endpoint for front-end and download upload service to consume
- this endpoint will upload post to the canisters as well as push the event data

**Comment by Natasha-GB** [comment]
Event Instrumentation Issue - https://github.com/orgs/go-bazzinga/projects/6/views/4?pane=issue&itemId=72507109

**Comment by Natasha-GB** [comment]
- Higher priority

**Comment by harshitasrivastav28** [comment]
- Ravi to take up integration part as well

**Comment by ravibazz** [comment]
Fixed in PR #45
