### ISSUE TITLE
Create Infrastructure for PNs in YRAL

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/off-chain-agent#43]
**Objective**: Create an infra for sending out **push and in-app** notifications to the users

**Components**: The expected components of the notifications will be:

- A placeholder for update the thumbnail image in the PN
- A header of the PN (Optional)
- A subtext of the PN
- Capability to add emojis in the texts which we can write
- Capability to have variable inputs in the test fields e.g. Congratulations! You won <var> tokens on <var> video.
- Capability to add a URL/Deeplinks in the PN  e.g. You won <var> tokens for referring a friend. Check it out <var link>

Potential sample Use Cases:

- As a user playing a HON game, as soon as I win in the game I should be notified the amount won and my winning status
- As a user, who referred a friend and whose friend joined I should be notified that I have won 1000 COYNs for referring a friend ob YRAL app
- As a user, who has signed up on the app but did not open the app in last 3 days I should be notified I am missing out amazing offers and log in today

Trigger condition for notifications:

- Trigger condition of the notifications should be linked to events which can be actions performed by users on frontend or can be backend computed 
- E.g. of frontend event - when lurker clicks on a like button trigger a notification to creator that <var> has liked your video
- E.g. of backend computed event - User has been allocated 1000 COYNs for winning a HON game

Use case document: https://docs.google.com/document/d/1ZrDXBTeiIVINaPHMmt1bPgEhz3PEnF_zDYm1DrvWeZ4/edit

Sample examples only for reference:
![Image](https://github.com/user-attachments/assets/ece6f924-cbf9-4d1b-acca-e4871e70cf17)
![Image](https://github.com/user-attachments/assets/256ae20c-ef53-4694-8992-44ca21565d98)

**Comment by Natasha-GB** [comment]
- Authentication part to be added
- Start with FCM and understand events handling

**Comment by harshitasrivastav28** [comment]
- Add type in the events so that off-chain agents can react to it
- Refine the list and link it here for dev @harshitasrivastav28 to fo

**Comment by Natasha-GB** [comment]
- Basic infrastructure is completed

Next steps:
- Events integration
- Device groups to be evaluated
- FE request mapping

**Comment by debjit-bhowal-rs** [comment]
Implementation log notif types, as shared by @harshitasrivastav28:
- [ ] First Like for video
- [ ] Like Video
- [ ] Share Video
- [ ] Viewed Video
- [ ] Video Uploaded
- [ ] All HON notifs (Pending event additions on FE)
- [ ] Others

**Comment by harshitasrivastav28** [comment]
- All of the one target event has been handled has been done
- If any principal has multiple device store the recent used device in its canister.

**Comment by debjit-bhowal-rs** [comment]
above PR is only on offchain agents, integrations on FE and canister under works

**Comment by Natasha-GB** [comment]
- Off chain agent PR pushed and reviews
- BE canister - basic functionality added, candidate types to added and FE integration pending
